import PDFDocument from 'pdfkit';
import logger from '../utils/logger.js';

export async function generateTranscriptPdf(transcript, metadata = {}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
        info: {
          Title: `${metadata.title || 'AI News Podcast'} - Transcript`,
          Author: process.env.PODCAST_HOST_NAME || 'Alex',
          Subject: 'AI News Podcast Transcript'
        }
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        logger.info(`PDF generated: ${(buffer.length / 1024).toFixed(1)} KB`);
        resolve(buffer);
      });
      doc.on('error', reject);

      // Header
      doc.fontSize(20)
        .font('Helvetica-Bold')
        .text(process.env.PODCAST_SHOW_NAME || 'AI Daily Digest', { align: 'center' });

      doc.moveDown(0.5);
      doc.fontSize(14)
        .font('Helvetica')
        .text(`Episode #${metadata.episodeNumber || ''}`, { align: 'center' });

      doc.fontSize(12)
        .fillColor('#666666')
        .text(metadata.date || new Date().toLocaleDateString(), { align: 'center' });

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
      doc.moveDown(1);

      // Topics
      if (metadata.topics && metadata.topics.length > 0) {
        doc.fontSize(10)
          .fillColor('#0066cc')
          .text(`Topics: ${metadata.topics.join(' • ')}`, { align: 'center' });
        doc.moveDown(1);
      }

      // Transcript body
      doc.fillColor('#333333');
      const lines = transcript.split('\n');

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.5);
          continue;
        }

        // Timestamps
        if (trimmed.match(/^\[\d{2}:\d{2}\]/)) {
          doc.moveDown(0.5);
          doc.fontSize(9)
            .fillColor('#999999')
            .text(trimmed);
          doc.fillColor('#333333');
          continue;
        }

        // Section headers (INTRO, STORY, OUTRO)
        if (trimmed.match(/^(INTRO|STORY|SEGMENT|OUTRO|CONCLUSION)/i)) {
          doc.moveDown(0.5);
          doc.fontSize(12)
            .font('Helvetica-Bold')
            .text(trimmed);
          doc.font('Helvetica');
          continue;
        }

        // Regular text
        doc.fontSize(11)
          .text(trimmed, { lineGap: 3 });
      }

      // Footer
      doc.moveDown(2);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
      doc.moveDown(0.5);
      doc.fontSize(9)
        .fillColor('#999999')
        .text(`Generated by ${process.env.PODCAST_SHOW_NAME || 'AI Daily Digest'} • ${new Date().toISOString()}`, { align: 'center' });

      doc.end();
    } catch (error) {
      logger.error('PDF generation failed', { error: error.message });
      reject(error);
    }
  });
}

export default { generateTranscriptPdf };
